const MAPPING = [
  {
    id: '7',
    name: 'Hauts-De-France',
    shape: 'circle',
    radius: 40,
    x1: '52%',
    y1: '10%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '9',
    name: 'Normandie',
    shape: 'circle',
    radius: 33,
    x1: '33%',
    y1: '18%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '8',
    name: 'Ile-de-France',
    shape: 'circle',
    radius: 25,
    x1: '53%',
    y1: '23%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '6',
    name: 'Grand-Est',
    shape: 'circle',
    radius: 65,
    x1: '72%',
    y1: '16%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '3',
    name: 'Bretagne',
    shape: 'circle',
    radius: 50,
    x1: '5%',
    y1: '23%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '12',
    name: 'Pays-De-La-Loire',
    shape: 'circle',
    radius: 40,
    x1: '24%',
    y1: '33%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '4',
    name: 'Centre',
    shape: 'circle',
    radius: 50,
    x1: '43%',
    y1: '33%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '2',
    name: 'Bourgogne-Franche-Compté',
    shape: 'circle',
    radius: 50,
    x1: '65%',
    y1: '35%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '10',
    name: 'Nouvelle-Aquitaine',
    shape: 'circle',
    radius: 80,
    x1: '23%',
    y1: '48%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '1',
    name: 'Auvergne-Rhône-Alpes',
    shape: 'circle',
    radius: 67,
    x1: '62%',
    y1: '49%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '11',
    name: 'Occitanie',
    shape: 'circle',
    radius: 70,
    x1: '42%',
    y1: '67%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '13',
    name: 'Provence-alpes',
    shape: 'circle',
    radius: 45,
    x1: '80%',
    y1: '67%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '5',
    name: 'Corse',
    shape: 'circle',
    radius: 40,
    x1: '87%',
    y1: '85%',
    prefill: 'transparent',
    fill: 'blue',
  },
];


export default MAPPING;
