const MAPPING = [
  {
    id: '7',
    key: '7_1',
    name: 'Hauts-de-France',
    shape: 'circle',
    radius: 40,
    x1: '52%',
    y1: '10%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '9',
    key: '9_1',
    name: 'Normandie',
    shape: 'circle',
    radius: 40,
    x1: '25%',
    y1: '18%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '9',
    key: '9_2',
    name: 'Normandie',
    shape: 'circle',
    radius: 40,
    x1: '35%',
    y1: '15%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '8',
    key: '8_1',
    name: 'Île-de-France',
    shape: 'circle',
    radius: 25,
    x1: '53%',
    y1: '23%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '6',
    key: '6_1',
    name: 'Grand-Est',
    shape: 'circle',
    radius: 65,
    x1: '65%',
    y1: '16%',
    prefill: 'transparent',
    fill: 'blue',
  },
   {
    id: '6',
    key: '6_2',
    name: 'Grand-Est',
    shape: 'circle',
    radius: 65,
    x1: '80%',
    y1: '16%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '3',
    key: '3_1',
    name: 'Bretagne',
    shape: 'circle',
    radius: 50,
    x1: '0%',
    y1: '23%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '3',
    key: '3_2',
    name: 'Bretagne',
    shape: 'circle',
    radius: 50,
    x1: '10%',
    y1: '23%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '12',
    key: '12_1',
    name: 'Pays-de-la-Loire',
    shape: 'circle',
    radius: 40,
    x1: '20%',
    y1: '36%',
    prefill: 'transparent',
    fill: 'blue',
  },
   {
    id: '12',
    key: '12_2',
    name: 'Pays-de-la-Loire',
    shape: 'circle',
    radius: 40,
    x1: '28%',
    y1: '30%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '4',
    key: '4_1',
    name: 'Centre-Val de Loire',
    shape: 'circle',
    radius: 50,
    x1: '43%',
    y1: '33%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '2',
    key: '2_1',
    name: 'Bourgogne-Franche-Comté',
    shape: 'circle',
    radius: 50,
    x1: '65%',
    y1: '35%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '10',
    key: '10_1',
    name: 'Nouvelle-Aquitaine',
    shape: 'circle',
    radius: 70,
    x1: '30%',
    y1: '45%',
    prefill: 'transparent',
    fill: 'blue',
  },
   {
    id: '10',
    key: '10_2',
    name: 'Nouvelle-Aquitaine',
    shape: 'circle',
    radius: 70,
    x1: '16%',
    y1: '60%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '1',
    key: '1_1',
    name: 'Auvergne-Rhône-Alpes',
    shape: 'circle',
    radius: 67,
    x1: '62%',
    y1: '49%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '11',
    key: '11_1',
    name: 'Occitanie',
    shape: 'circle',
    radius: 70,
    x1: '42%',
    y1: '67%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '13',
    key: '13_1',
    name: "Provence-Alpes-Côte d'Azur",
    shape: 'circle',
    radius: 45,
    x1: '80%',
    y1: '67%',
    prefill: 'transparent',
    fill: 'blue',
  },
  {
    id: '5',
    key: '5_1',
    name: 'Corse',
    shape: 'circle',
    radius: 40,
    x1: '87%',
    y1: '82%',
    prefill: 'transparent',
    fill: 'blue',
  },
   {
    id: '5',
    key: '5_2',
    name: 'Corse',
    shape: 'circle',
    radius: 40,
    x1: '87%',
    y1: '90%',
    prefill: 'transparent',
    fill: 'blue',
  },
];


export default MAPPING;
